### ISSUE TITLE
Game crash upon entering specific servers 

### ISSUE THREAD

**Issue by TicTecOfficial** [VexorMC/sodium#2]
### Bug Description

NOTE: this issue can _definitely_ be universal, but i mention the issue in the context "specific servers" because the server may be giving the client things that it doesn't know how to render, and the game crashes too quickly for me to tell what exactly causes the game to crash.

### Reproduction Steps

- launch minecraft with the mod installed
- join the server "premium.blocksmc.com" and go to the main lobby (the only way i managed to trigger the crash)

### Log File

MultiMC version: 0.7.0-4018

Launched instance in online mode

authserver.mojang.com resolves to:
    [N/A]

sessionserver.mojang.com resolves to:
    [2620:1ec:bdf::59, 13.107.246.59]

textures.minecraft.net resolves to:
    [2620:1ec:bdf::59, 13.107.246.59]

api.minecraftservices.com resolves to:
    [2620:1ec:bdf::59, 13.107.246.59]

Minecraft folder is:
C:/Users/grape/Downloads/MultiMC/instances/legacyfabric-1.8.9-loader.0.16.7/.minecraft

Java path is:
C:/Program Files/Common Files/Oracle/Java/javapath/javaw.exe

Checking Java version...
Java is version 21.0.3, using amd64 architecture, from Oracle Corporation.

Main Class:
  net.fabricmc.loader.impl.launch.knot.KnotClient

Native path:
  C:/Users/grape/Downloads/MultiMC/instances/legacyfabric-1.8.9-loader.0.16.7/natives

Libraries:
  C:/Users/grape/Downloads/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  C:/Users/grape/Downloads/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  C:/Users/grape/Downloads/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4+legacyfabric.8/lwjgl-2.9.4+legacyfabric.8.jar
  C:/Users/grape/Downloads/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4+legacyfabric.8/lwjgl_util-2.9.4+legacyfabric.8.jar
  C:/Users/grape/Downloads/MultiMC/libraries/com/mojang/netty/1.8.8/netty-1.8.8.jar
  C:/Users/grape/Downloads/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  C:/Users/grape/Downloads/MultiMC/libraries/net/java/dev/jna/jna/3.4.0/jna-3.4.0.jar
  C:/Users/grape/Downloads/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  C:/Users/grape/Downloads/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  C:/Users/grape/Downloads/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/4.6/jopt-simple-4.6.jar
  C:/Users/grape/Downloads/MultiMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  C:/Users/grape/Downloads/MultiMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  C:/Users/grape/Downloads/MultiMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  C:/Users/grape/Downloads/MultiMC/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  C:/Users/grape/Downloads/MultiMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  C:/Users/grape/Downloads/MultiMC/libraries/io/netty/netty-all/4.0.23.Final/netty-all-4.0.23.Final.jar
  C:/Users/grape/Downloads/MultiMC/libraries/com/google/guava/guava/17.0/guava-17.0.jar
  C:/Users/grape/Downloads/MultiMC/libraries/org/apache/commons/commons-lang3/3.3.2/commons-lang3-3.3.2.jar
  C:/Users/grape/Downloads/MultiMC/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar
  C:/Users/grape/Downloads/MultiMC/libraries/commons-codec/commons-codec/1.9/commons-codec-1.9.jar
  C:/Users/grape/Downloads/MultiMC/libraries/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar
  C:/Users/grape/Downloads/MultiMC/libraries/com/mojang/authlib/1.5.21/authlib-1.5.21.jar
  C:/Users/grape/Downloads/MultiMC/libraries/com/mojang/realms/1.7.59/realms-1.7.59.jar
  C:/Users/grape/Downloads/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/Users/grape/Downloads/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/Users/grape/Downloads/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/Users/grape/Downloads/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/Users/grape/Downloads/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.0-beta9-fixed/log4j-api-2.0-beta9-fixed.jar
  C:/Users/grape/Downloads/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.0-beta9-fixed/log4j-core-2.0-beta9-fixed.jar
  C:/Users/grape/Downloads/MultiMC/libraries/tv/twitch/twitch/6.5/twitch-6.5.jar
  C:/Users/grape/Downloads/MultiMC/libraries/net/legacyfabric/intermediary/1.8.9/intermediary-1.8.9.jar
  C:/Users/grape/Downloads/MultiMC/libraries/org/ow2/asm/asm/9.7.1/asm-9.7.1.jar
  C:/Users/grape/Downloads/MultiMC/libraries/org/ow2/asm/asm-analysis/9.7.1/asm-analysis-9.7.1.jar
  C:/Users/grape/Downloads/MultiMC/libraries/org/ow2/asm/asm-commons/9.7.1/asm-commons-9.7.1.jar
  C:/Users/grape/Downloads/MultiMC/libraries/org/ow2/asm/asm-tree/9.7.1/asm-tree-9.7.1.jar
  C:/Users/grape/Downloads/MultiMC/libraries/org/ow2/asm/asm-util/9.7.1/asm-util-9.7.1.jar
  C:/Users/grape/Downloads/MultiMC/libraries/net/fabricmc/sponge-mixin/0.15.3+mixin.0.8.7/sponge-mixin-0.15.3+mixin.0.8.7.jar
  C:/Users/grape/Downloads/MultiMC/libraries/net/fabricmc/fabric-loader/0.16.7/fabric-loader-0.16.7.jar
  C:/Users/grape/Downloads/MultiMC/libraries/com/mojang/minecraft/1.8.9/minecraft-1.8.9-client.jar

Native libraries:
  C:/Users/grape/Downloads/MultiMC/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar
  C:/Users/grape/Downloads/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4+legacyfabric.8/lwjgl-platform-2.9.4+legacyfabric.8-natives-windows.jar
  C:/Users/grape/Downloads/MultiMC/libraries/tv/twitch/twitch-platform/6.5/twitch-platform-6.5-natives-windows-64.jar
  C:/Users/grape/Downloads/MultiMC/libraries/tv/twitch/twitch-external-platform/4.5/twitch-external-platform-4.5-natives-windows-64.jar

Mods:
  [❌] Carbon-1.0.1.jar.disabled (disabled)
  [✔️] LegacyEnhance-1.0.0.jar
  [✔️] legacy-fabric-api-1.10.2.jar
  [✔️] legacy-fixes-1.0.1.jar
  [✔️] legacy-modmenu-1.1.0.jar
  [✔️] netfix.jar
  [❌] oldium-fabric-1.8.9-JAVA8FIX.jar.disabled (disabled)
  [✔️] sodium-fabric-0.6.6-snapshot+mc1.8.9-build.58.jar

Params:
  --username T1ckerR --version 1.8.9 --gameDir C:/Users/grape/Downloads/MultiMC/instances/legacyfabric-1.8.9-loader.0.16.7/.minecraft --assetsDir C:/Users/grape/Downloads/MultiMC/assets --assetIndex 1.8 --uuid <PROFILE ID> --accessToken <ACCESS TOKEN> --userProperties {} --userType msa

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx1024m, -Duser.language=en]

Minecraft process ID: 8692

Using onesix launcher.

[17:55:22] [main/INFO]: Loading Minecraft 1.8.9 with Fabric Loader 0.16.7
[17:55:22] [ForkJoinPool-1-worker-6/WARN]: Mod netfix uses the version ${version} which isn't compatible with Loader's extended semantic version format (Could not parse version number component '${version}'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[17:55:22] [main/INFO]: Loading 39 mods:
	- fabricloader 0.16.7
	   \-- mixinextras 0.4.1
	- java 21
	- legacy-fabric-api 1.10.2
	   |-- legacy-fabric-api-base 1.1.0+1.8.9+7c545fdbe239
	   |-- legacy-fabric-api-base-common 1.1.0+7c545fdbe692
	   |-- legacy-fabric-command-api-v1 1.0.1+052b5678db92
	   |-- legacy-fabric-command-api-v2 1.0.2+1.8.9+6c60a8d10039
	   |-- legacy-fabric-crash-report-info-v1 1.0.0+7c545fdb4992
	   |-- legacy-fabric-entity-events-v1 1.0.0+1.8.9+095a57590739
	   |-- legacy-fabric-entity-events-v1-common 1.0.0+095a57593e92
	   |-- legacy-fabric-gamerule-api-v1 1.0.0+7c545fdb4c92
	   |-- legacy-fabric-item-groups-v1 2.1.0+1.8.9+052b5678db39
	   |-- legacy-fabric-item-groups-v1-common 2.1.0+052b56784e92
	   |-- legacy-fabric-keybinding-api-v1 1.1.1+1.8.9+281301ea2839
	   |-- legacy-fabric-keybinding-api-v1-common 1.1.1+281301ea5992
	   |-- legacy-fabric-lifecycle-events-v1 1.1.0+1.8.9+052b5678f739
	   |-- legacy-fabric-lifecycle-events-v1-common 1.1.0+052b56787c92
	   |-- legacy-fabric-logger-api-v1 1.0.4+7c545fdb7292
	   |-- legacy-fabric-networking-api-v1 2.0.2+1.8.9+7c545fdb1839
	   |-- legacy-fabric-networking-api-v1-common 2.0.2+052b56786192
	   |-- legacy-fabric-permissions-api-v1 1.1.0+1.8.9+052b56787839
	   |-- legacy-fabric-permissions-api-v1-common 1.1.0+052b5678a792
	   |-- legacy-fabric-registry-sync-api-v1 2.2.0+1.8.9+7c545fdb6e39
	   |-- legacy-fabric-registry-sync-api-v1-common 2.2.0+1c4806cdcb92
	   |-- legacy-fabric-rendering-api-v1 1.0.0+1.8.9+7c545fdbba39
	   |-- legacy-fabric-rendering-api-v1-common 1.0.0+7c545fdb6992
	   |-- legacy-fabric-resource-loader-v1 2.2.1+1.8.9+7c545fdb4d39
	   \-- legacy-fabric-resource-loader-v1-common 2.2.1+052b5678f192
	- legacy-fixes 1.0.1
	- legacyenhance 1.0.0
	   |-- axolotlclientconfig 2.1.9+1.8.9
	   |    |-- io_github_axolotlclient_axolotlclient-config_common_ 2.1.9
	   |    \-- legacyclientcommands 1.0.0
	   \-- io_github_axolotlclient_axolotlclient-config_axolod6a22e2119cdc0 2.1.9
	- minecraft 1.8.9
	- modmenu 1.1.0
	- netfix ${version}
	- sodium 0.6.6-snapshot+mc1.8.9-build.58
[17:55:23] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.7 Source=file:/C:/Users/grape/Downloads/MultiMC/libraries/net/fabricmc/sponge-mixin/0.15.3+mixin.0.8.7/sponge-mixin-0.15.3+mixin.0.8.7.jar Service=Knot/Fabric Env=CLIENT
[17:55:23] [main/INFO]: Compatibility level set to JAVA_17
[17:55:23] [main/INFO]: Loaded configuration file for Radium: 43 options available, 0 override(s) found
[LWJGL] Detected environment: Os:windows Arch: amd64 Java: 21.0.3
Completely ignored arguments: [--versionType, Fabric]
[17:55:26] [Client thread/INFO]: Setting user: T1ckerR
[17:55:26] [Client thread/INFO]: (Session ID is token:<ACCESS TOKEN>:<PROFILE ID>)
[17:55:30] [Client thread/INFO]: [LegacyEnhance] Initalized
[17:55:30] [Client thread/INFO]: LWJGL Version: 2.9.4+legacyfabric
[17:55:31] [Client thread/INFO]: Reloading ResourceManager: Default, AxolotlClientConfig, Fabric Loader, AxolotlClientConfig-common, common, Legacy Fabric API, Legacy Fabric API Base, Legacy Fabric API Base Common, Legacy Fabric Command API (V1), Legacy Fabric Command API (v2), Legacy Fabric Crash Report Info (v1), Legacy Fabric Entity Events (V1), Legacy Fabric Entity Events (V1), Fabric Gamerule API (v1), Legacy Fabric Item Groups (V1), Legacy Fabric Item Groups (V1), Legacy Fabric Keybinding API (V1), Legacy Fabric Lifecycle Events (V1), Legacy Fabric Lifecycle Events (V1), Legacy Fabric Logger API (v1), Legacy Fabric Networking API (v1), Legacy Fabric Networking API (v1), Legacy Fabric Permissions API (v2), Legacy Fabric Permissions API (v1), Legacy Fabric Registry Sync API (V1), Legacy Fabric Registry Sync API (V1), Legacy Fabric Rendering API (V1), Legacy Fabric Rendering API (V1), Legacy Fabric Resource Loader (V1), Legacy Fabric Resource Loader (V1) Common, Legacy Fixes, Legacy Client Commands, LegacyEnhance, Mod Menu, Sodium
[17:55:32] [Sound Library Loader/INFO]: Starting up SoundSystem...
[17:55:32] [Thread-6/INFO]: Initializing LWJGL OpenAL
[17:55:32] [Thread-6/INFO]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[17:55:32] [Thread-6/INFO]: OpenAL initialized.
[17:55:32] [Sound Library Loader/INFO]: Sound engine started
[17:55:33] [Client thread/INFO]: Created: 512x512 textures-atlas
[17:55:38] [Client thread/INFO]: Connecting to premium.blocksmc.com, 25565
[17:55:40] [Client thread/INFO]: Started 10 worker threads
[17:55:40] [Client thread/INFO]: Mapping buffer of length 16777216
[17:55:41] [Client thread/INFO]: [CHAT] 
[17:55:41] [Client thread/INFO]: [CHAT] 
[17:55:41] [Client thread/INFO]: [CHAT] 
[17:55:41] [Client thread/INFO]: [CHAT] 
[17:55:41] [Client thread/INFO]: [CHAT] 
[17:55:41] [Client thread/INFO]: [CHAT] 
[17:55:41] [Client thread/INFO]: [CHAT] 
[17:55:41] [Client thread/INFO]: [CHAT] 
[17:55:41] [Client thread/INFO]: [CHAT] 
[17:55:41] [Client thread/INFO]: [CHAT] 
[17:55:41] [Client thread/INFO]: [CHAT] 
[17:55:41] [Client thread/INFO]: [CHAT] 
[17:55:41] [Client thread/INFO]: [CHAT] 
[17:55:41] [Client thread/INFO]: [CHAT] 
[17:55:41] [Client thread/INFO]: [CHAT] 
[17:55:41] [Client thread/INFO]: [CHAT] 
[17:55:41] [Client thread/INFO]: [CHAT] 
[17:55:41] [Client thread/INFO]: [CHAT] 
[17:55:41] [Client thread/INFO]: [CHAT] 
[17:55:41] [Client thread/INFO]: [CHAT] 
[17:55:41] [Client thread/INFO]: [CHAT] 
[17:55:41] [Client thread/INFO]: [CHAT] 
[17:55:41] [Client thread/INFO]: [CHAT] 
[17:55:41] [Client thread/INFO]: [CHAT] 
[17:55:41] [Client thread/INFO]: [CHAT] 
[17:55:41] [Client thread/INFO]: [CHAT] 
[17:55:41] [Client thread/INFO]: [CHAT] 
[17:55:41] [Client thread/INFO]: [CHAT] 
[17:55:41] [Client thread/INFO]: [CHAT] 
[17:55:41] [Client thread/INFO]: [CHAT] 
[17:55:41] [Client thread/INFO]: [CHAT] 
[17:55:41] [Client thread/INFO]: [CHAT] 
[17:55:41] [Client thread/INFO]: [CHAT] 
[17:55:41] [Client thread/INFO]: [CHAT] 
[17:55:41] [Client thread/INFO]: [CHAT] 
[17:55:41] [Client thread/INFO]: [CHAT] 
[17:55:41] [Client thread/INFO]: [CHAT] 
[17:55:41] [Client thread/INFO]: [CHAT] 
[17:55:41] [Client thread/INFO]: [CHAT] 
[17:55:41] [Client thread/INFO]: [CHAT] 
[17:55:41] [Client thread/INFO]: [CHAT] 
[17:55:41] [Client thread/INFO]: [CHAT] 
[17:55:41] [Client thread/INFO]: [CHAT] 
[17:55:41] [Client thread/INFO]: [CHAT] 
[17:55:41] [Client thread/INFO]: [CHAT] 
[17:55:41] [Client thread/INFO]: [CHAT] 
[17:55:41] [Client thread/INFO]: [CHAT] 
[17:55:41] [Client thread/INFO]: [CHAT] 
[17:55:41] [Client thread/INFO]: [CHAT] 
[17:55:41] [Client thread/INFO]: [CHAT] 
[17:55:41] [Client thread/INFO]: [CHAT] 
[17:55:41] [Client thread/INFO]: [CHAT] 
[17:55:41] [Client thread/INFO]: [CHAT] 
[17:55:41] [Client thread/INFO]: [CHAT]                         Welcome to BlocksMC
[17:55:41] [Client thread/INFO]: [CHAT]                 We have 871 players at our network
[17:55:41] [Client thread/INFO]: [CHAT] 
[17:55:41] [Client thread/INFO]: [CHAT]                          Check out these links:
[17:55:41] [Client thread/INFO]: [CHAT]      Website - Rules - Store - Support - Discord - Vote
[17:55:41] [Client thread/INFO]: [CHAT] 
[17:55:41] [Client thread/INFO]: [CHAT]                                Have Fun â¤
[17:55:41] [Client thread/INFO]: [CHAT] 
[17:55:41] [Client thread/INFO]: Started 10 worker threads
[17:55:41] [Client thread/INFO]: Mapping buffer of length 16777216
[17:55:41] [Client thread/INFO]: Stopping worker threads
[17:55:41] [Client thread/INFO]: Started 10 worker threads
[17:55:41] [Client thread/INFO]: Mapping buffer of length 16777216
[17:55:41] [Client thread/INFO]: Started 10 worker threads
[17:55:41] [Client thread/INFO]: Mapping buffer of length 16777216
[17:55:41] [Client thread/INFO]: Stopping worker threads
[17:55:41] [Client thread/INFO]: Started 10 worker threads
[17:55:41] [Client thread/INFO]: Mapping buffer of length 16777216
[17:55:41] [Client thread/INFO]: Started 10 worker threads
[17:55:41] [Client thread/INFO]: Mapping buffer of length 16777216
[17:55:41] [Client thread/INFO]: Stopping worker threads
[17:55:41] [Client thread/INFO]: Started 10 worker threads
[17:55:41] [Client thread/INFO]: Mapping buffer of length 16777216
[17:55:41] [Client thread/INFO]: Started 10 worker threads
[17:55:41] [Client thread/INFO]: Mapping buffer of length 16777216
[17:55:41] [Client thread/INFO]: Stopping worker threads
[17:55:41] [Client thread/INFO]: Started 10 worker threads
[17:55:41] [Client thread/INFO]: Mapping buffer of length 16777216
[17:55:41] [Client thread/INFO]: Started 10 worker threads
[17:55:41] [Client thread/INFO]: Mapping buffer of length 16777216
[17:55:41] [Client thread/INFO]: Stopping worker threads
[17:55:41] [Client thread/INFO]: Started 10 worker threads
[17:55:41] [Client thread/INFO]: Mapping buffer of length 16777216
[17:55:43] [Client thread/INFO]: Mapping buffer of length 399264
[17:55:43] [Chunk Render Task Executor #5/ERROR]: Chunk build failed
net.minecraft.class_875: Encountered exception while building chunk meshes
	at knot//net.caffeinemc.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.fillCrashInfo(ChunkBuilderMeshingTask.java:219) ~[sodium-fabric-0.6.6-snapshot+mc1.8.9-build.58.jar:?]
	at knot//net.caffeinemc.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:151) ~[sodium-fabric-0.6.6-snapshot+mc1.8.9-build.58.jar:?]
	at knot//net.caffeinemc.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:51) ~[sodium-fabric-0.6.6-snapshot+mc1.8.9-build.58.jar:?]
	at knot//net.caffeinemc.mods.sodium.client.render.chunk.compile.executor.ChunkJobTyped.execute(ChunkJobTyped.java:45) ~[sodium-fabric-0.6.6-snapshot+mc1.8.9-build.58.jar:?]
	at knot//net.caffeinemc.mods.sodium.client.render.chunk.compile.executor.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:215) ~[sodium-fabric-0.6.6-snapshot+mc1.8.9-build.58.jar:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 28 out of bounds for length 28
	at knot//net.minecraft.class_2437.getVertexNormal(class_2437.java:570) ~[client-intermediary.jar:?]
	at knot//net.caffeinemc.mods.sodium.client.model.quad.ModelQuadView.getAccurateNormal(ModelQuadView.java:126) ~[sodium-fabric-0.6.6-snapshot+mc1.8.9-build.58.jar:?]
	at knot//net.caffeinemc.mods.sodium.client.model.light.smooth.SmoothLightPipeline.applyIrregularFace(SmoothLightPipeline.java:256) ~[sodium-fabric-0.6.6-snapshot+mc1.8.9-build.58.jar:?]
	at knot//net.caffeinemc.mods.sodium.client.model.light.smooth.SmoothLightPipeline.calculate(SmoothLightPipeline.java:89) ~[sodium-fabric-0.6.6-snapshot+mc1.8.9-build.58.jar:?]
	at knot//net.caffeinemc.mods.sodium.client.render.chunk.compile.pipeline.BlockRenderer.getVertexLight(BlockRenderer.java:141) ~[sodium-fabric-0.6.6-snapshot+mc1.8.9-build.58.jar:?]
	at knot//net.caffeinemc.mods.sodium.client.render.chunk.compile.pipeline.BlockRenderer.renderQuadList(BlockRenderer.java:126) ~[sodium-fabric-0.6.6-snapshot+mc1.8.9-build.58.jar:?]
	at knot//net.caffeinemc.mods.sodium.client.render.chunk.compile.pipeline.BlockRenderer.renderModel(BlockRenderer.java:105) ~[sodium-fabric-0.6.6-snapshot+mc1.8.9-build.58.jar:?]
	at knot//net.caffeinemc.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:119) ~[sodium-fabric-0.6.6-snapshot+mc1.8.9-build.58.jar:?]
	... 4 more
Negative index in crash report handler (12/13)
[17:55:43] [Client thread/INFO]: Stopping!
[17:55:43] [Client thread/INFO]: SoundSystem shutting down...
[17:55:43] [Client thread/WARN]: Author: Paul Lamb, www.paulscode.com
Process exited with exit code 0 (0x0).
Please note that usually neither the exit code, nor its description are enough to diagnose issues!
Always upload the entire log and not just the exit code.
Clipboard copy at: 30 Dec 2024 17:55:52 +0800

### Crash Report

[17:55:43] [Chunk Render Task Executor #5/ERROR]: Chunk build failed
net.minecraft.class_875: Encountered exception while building chunk meshes
	at knot//net.caffeinemc.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.fillCrashInfo(ChunkBuilderMeshingTask.java:219) ~[sodium-fabric-0.6.6-snapshot+mc1.8.9-build.58.jar:?]
	at knot//net.caffeinemc.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:151) ~[sodium-fabric-0.6.6-snapshot+mc1.8.9-build.58.jar:?]
	at knot//net.caffeinemc.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:51) ~[sodium-fabric-0.6.6-snapshot+mc1.8.9-build.58.jar:?]
	at knot//net.caffeinemc.mods.sodium.client.render.chunk.compile.executor.ChunkJobTyped.execute(ChunkJobTyped.java:45) ~[sodium-fabric-0.6.6-snapshot+mc1.8.9-build.58.jar:?]
	at knot//net.caffeinemc.mods.sodium.client.render.chunk.compile.executor.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:215) ~[sodium-fabric-0.6.6-snapshot+mc1.8.9-build.58.jar:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 28 out of bounds for length 28
	at knot//net.minecraft.class_2437.getVertexNormal(class_2437.java:570) ~[client-intermediary.jar:?]
	at knot//net.caffeinemc.mods.sodium.client.model.quad.ModelQuadView.getAccurateNormal(ModelQuadView.java:126) ~[sodium-fabric-0.6.6-snapshot+mc1.8.9-build.58.jar:?]
	at knot//net.caffeinemc.mods.sodium.client.model.light.smooth.SmoothLightPipeline.applyIrregularFace(SmoothLightPipeline.java:256) ~[sodium-fabric-0.6.6-snapshot+mc1.8.9-build.58.jar:?]
	at knot//net.caffeinemc.mods.sodium.client.model.light.smooth.SmoothLightPipeline.calculate(SmoothLightPipeline.java:89) ~[sodium-fabric-0.6.6-snapshot+mc1.8.9-build.58.jar:?]
	at knot//net.caffeinemc.mods.sodium.client.render.chunk.compile.pipeline.BlockRenderer.getVertexLight(BlockRenderer.java:141) ~[sodium-fabric-0.6.6-snapshot+mc1.8.9-build.58.jar:?]
	at knot//net.caffeinemc.mods.sodium.client.render.chunk.compile.pipeline.BlockRenderer.renderQuadList(BlockRenderer.java:126) ~[sodium-fabric-0.6.6-snapshot+mc1.8.9-build.58.jar:?]
	at knot//net.caffeinemc.mods.sodium.client.render.chunk.compile.pipeline.BlockRenderer.renderModel(BlockRenderer.java:105) ~[sodium-fabric-0.6.6-snapshot+mc1.8.9-build.58.jar:?]
	at knot//net.caffeinemc.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:119) ~[sodium-fabric-0.6.6-snapshot+mc1.8.9-build.58.jar:?]
	... 4 more

**Comment by Luna0x01** [comment]
workaround has been implemented, but this will remain open until we figure out the root cause

**Comment by Luna0x01** [comment]
issue perhaps identified, @Decencies thinks this might be because of the `enhanced` smooth lighting parameter

**Comment by Luna0x01** [comment]
Recent testing has shown this issue does not occur anymore.

Please re-open if faced again.
